import { createQuestion, findElementByAtomicNumber, getSearchPool, pickQuizElements } from "./elements.js";
import { renderAtomSvg } from "./atom-renderer.js";
import { compressDataUrl, compressImage } from "./image-utils.js";
import { createDrawingCanvas } from "./drawing-canvas.js";
import { createSubmissionState, getActiveResult, setSubmissionMode } from "./submission-editor.js";
import { createAdminPopupPage, groupParticipationRecords } from "./admin-view-model.js";
import { makeDownloadFilename } from "./auth-utils.js";
import {
  completeSession, createSession, deleteParticipation, ensureAnonymousStudent, getSettings,
  grantSubmissionEdit, isCurrentUserAdmin, listFeedback, listSessions, listSessionSubmissions,
  listSubmissions, migrateLegacyVisibility, replaceSubmissionResult, saveFeedback, saveSettings,
  saveSubmission, setSessionPeerVisibility, signInAdmin, signOutAdmin
} from "./firebase-service.js";

const FIELD_LABELS = { atomicNumber:"원소 번호", name:"이름", symbol:"기호", protons:"양성자 수", neutrons:"중성자 수", electrons:"전자 수" };
const state = { profile:null, sessionId:null, questions:[], currentIndex:0, settings:{answerRevealEnabled:false,elementSearchEnabled:false}, submissions:[], feedback:[], editor:null, drawing:null, sessions:[], adminRecords:[], adminRecord:null, adminPage:0, quizHistoryActive:false };
const views = { start:document.querySelector("#studentStartView"), quiz:document.querySelector("#quizView"), results:document.querySelector("#resultsView"), myAnswers:document.querySelector("#myAnswersView"), search:document.querySelector("#searchView"), admin:document.querySelector("#adminView") };
const messageBox=document.querySelector("#messageBox");
const modalHost=document.querySelector("#modalHost");
document.querySelector("#adminOpenButton").addEventListener("click",()=>isCurrentUserAdmin()?renderAdminDashboard():renderAdminLogin());
window.addEventListener("popstate",handleBrowserBack);
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&modalHost.innerHTML)history.back();});
init();

async function init(){try{await ensureAnonymousStudent();await refreshSettings();}catch(error){showMessage(`인증 준비 실패: ${error.message}`,true);}renderStart();}
function showView(name){Object.values(views).forEach(view=>view.classList.remove("active-view"));views[name].classList.add("active-view");}
function showMessage(message,isError=false){messageBox.textContent=message;messageBox.classList.toggle("danger-text",isError);if(message)setTimeout(()=>messageBox.textContent===message&&(messageBox.textContent=""),4200);}
async function refreshSettings(){state.settings=await getSettings();}
function clean(value){return String(value??"").trim();}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[char]);}

function renderStart(){state.quizHistoryActive=false;views.start.innerHTML=`<section class="panel stack"><div><h2>학생 정보 입력</h2><p class="muted">학년, 반, 조, 번호, 이름을 입력한 뒤 시작하세요.</p></div><form id="startForm" class="stack"><div class="form-grid"><label>학년 <input name="gradeName" required placeholder="예: 1학년"></label><label>반 <input name="className" required placeholder="예: 1반"></label><label>조 <input name="teamName" required placeholder="예: 3조"></label><label>번호 <input name="studentNumber" inputmode="numeric" required placeholder="예: 12"></label><label>이름 <input name="studentName" required placeholder="예: 홍길동"></label></div><div class="actions"><button type="submit">게임 시작</button>${state.settings.elementSearchEnabled?`<button id="openSearchButton" class="secondary-button" type="button">원소 검색</button>`:""}</div></form></section>`;views.start.querySelector("#startForm").addEventListener("submit",handleStart);views.start.querySelector("#openSearchButton")?.addEventListener("click",renderSearch);showView("start");}
async function handleStart(event){event.preventDefault();const data=new FormData(event.currentTarget);const profile=Object.fromEntries(["gradeName","className","teamName","studentNumber","studentName"].map(key=>[key,clean(data.get(key))]));if(Object.values(profile).some(value=>!value))return showMessage("학생 정보를 모두 입력해 주세요.",true);event.submitter.disabled=true;try{state.profile=profile;state.sessionId=await createSession(profile);state.questions=pickQuizElements(3).map(createQuestion);state.currentIndex=0;history.pushState({quiz:true},"");state.quizHistoryActive=true;renderQuiz();}catch(error){showMessage(`시작 실패: ${error.message}`,true);}finally{event.submitter.disabled=false;}}
function renderQuiz(){const question=state.questions[state.currentIndex];state.editor=createSubmissionState();views.quiz.innerHTML=`<section class="panel stack"><div><p class="quiz-status">${state.currentIndex+1} / 3 문제</p><h2>제시된 정보를 보고 원자 모형을 그려보세요</h2></div><form id="quizForm" class="stack">${renderQuestionTable(question.element,question.blankFields)}${submissionEditorMarkup()}<div class="actions"><button type="submit">제출하고 다음으로</button></div></form></section>`;bindSubmissionEditor(views.quiz);views.quiz.querySelector("#quizForm").addEventListener("submit",handleQuestionSubmit);showView("quiz");}
function renderQuestionTable(element,blankFields){return `<div class="table-wrap"><table><thead><tr><th>항목</th><th>정보</th></tr></thead><tbody>${Object.keys(FIELD_LABELS).map(field=>`<tr><th>${FIELD_LABELS[field]}</th><td>${blankFields.includes(field)?`<input name="${field}" required aria-label="${FIELD_LABELS[field]} 입력">`:escapeHtml(element[field])}</td></tr>`).join("")}</tbody></table></div>`;}
function submissionEditorMarkup(existingImage=""){return `<div class="submission-mode" role="group" aria-label="제출 방식"><button data-mode="photo" class="secondary-button" type="button">사진 촬영/선택</button><button data-mode="canvas" type="button">캔버스에 그리기</button></div><section data-photo-panel hidden class="stack"><label>사진 촬영 또는 선택 <input data-photo-input type="file" accept="image/*"></label><img data-photo-preview class="preview-image" alt="선택한 사진 미리보기" ${existingImage?`src="${existingImage}"`:"hidden"}></section><section data-canvas-panel class="stack"><div class="drawing-toolbar"><button data-tool="black" type="button">검정</button><button data-tool="electron" class="secondary-button" type="button">전자</button><button data-tool="proton" class="secondary-button" type="button">양성자</button><button data-tool="neutron" class="secondary-button" type="button">중성자</button><button data-tool="eraser" class="secondary-button" type="button">지우개</button><button data-tool="pan" class="secondary-button" type="button">선택/이동</button><button data-fullscreen class="secondary-button" type="button">전체화면</button><button data-exit-fullscreen class="secondary-button" type="button">전체화면 닫기</button></div><div data-canvas-root class="drawing-viewport"></div></section>`;}
function bindSubmissionEditor(container,initial={}){state.editor=createSubmissionState(initial);const photoPanel=container.querySelector("[data-photo-panel]");const canvasPanel=container.querySelector("[data-canvas-panel]");const modeButtons=container.querySelectorAll("[data-mode]");const selectMode=mode=>{setSubmissionMode(state.editor,mode);photoPanel.hidden=mode!=="photo";canvasPanel.hidden=mode!=="canvas";modeButtons.forEach(button=>button.classList.toggle("secondary-button",button.dataset.mode!==mode));};modeButtons.forEach(button=>button.addEventListener("click",()=>selectMode(button.dataset.mode)));container.querySelector("[data-photo-input]").addEventListener("change",async event=>{const file=event.currentTarget.files[0];if(!file)return;try{state.editor.photoData=await compressImage(file);const preview=container.querySelector("[data-photo-preview]");preview.src=state.editor.photoData;preview.hidden=false;}catch(error){showMessage(error.message,true);}});state.drawing=createDrawingCanvas(container.querySelector("[data-canvas-root]"),()=>{state.editor.canvasDirty=true;});container.querySelectorAll("[data-tool]").forEach(button=>button.addEventListener("click",()=>{state.drawing.setTool(button.dataset.tool);container.querySelectorAll("[data-tool]").forEach(item=>item.classList.toggle("secondary-button",item!==button));}));container.querySelector("[data-fullscreen]").addEventListener("click",()=>{state.drawing.enterFullscreen();container.querySelectorAll("[data-tool]").forEach(item=>item.classList.toggle("secondary-button",item.dataset.tool!=="pan"));});container.querySelector("[data-exit-fullscreen]").addEventListener("click",()=>state.drawing.exitFullscreen());selectMode(initial.mode||"canvas");}
async function getEditorResult(){if(state.editor.mode==="canvas"){state.editor.canvasDirty=state.drawing.isDirty();if(state.editor.canvasDirty)state.editor.canvasData=await compressDataUrl(state.drawing.toDataUrl());}return getActiveResult(state.editor);}
async function handleQuestionSubmit(event){event.preventDefault();const question=state.questions[state.currentIndex];const data=new FormData(event.currentTarget);const studentAnswers=Object.fromEntries(question.blankFields.map(field=>[field,clean(data.get(field))]));const button=event.submitter;button.disabled=true;try{const result=await getEditorResult();await saveSubmission({sessionId:state.sessionId,...state.profile,questionIndex:state.currentIndex+1,elementNumber:question.element.atomicNumber,blankFields:question.blankFields,studentAnswers,...result});state.currentIndex+=1;if(state.currentIndex<3)return renderQuiz();await completeSession(state.sessionId);state.quizHistoryActive=false;showMessage("3문제 제출이 완료되었습니다.");await renderResults("team");}catch(error){showMessage(error.message,true);}finally{button.disabled=false;}}
async function handleBrowserBack(){if(modalHost.innerHTML)return closeAdminModal(false);if(!state.quizHistoryActive)return;history.pushState({quiz:true},"");if(!confirm("정말 취소하시겠습니까?"))return;try{await deleteParticipation(state.sessionId,{studentCancel:true});state.profile=null;state.sessionId=null;state.questions=[];state.quizHistoryActive=false;renderStart();}catch(error){showMessage(`취소 실패: ${error.message}`,true);}}

async function refreshClassData(admin=false){const [submissions,sessions]=await Promise.all([listSubmissions({admin}),admin?listSessions():Promise.resolve([])]);state.submissions=submissions;state.sessions=sessions;state.feedback=await listFeedback(state.submissions.map(item=>item.id),{admin});}
async function renderResults(scope="team"){await refreshSettings();await refreshClassData(false);const visible=scope==="team"?state.submissions.filter(item=>item.className===state.profile?.className&&item.teamName===state.profile?.teamName):state.submissions;views.results.innerHTML=`<section class="panel stack"><div><h2>${scope==="team"?"우리 조 결과":"전체 조 결과"}</h2><p class="muted">친구의 원자 모형을 보고 피드백을 남겨보세요.</p></div><div class="actions"><button id="myAnswersButton" type="button">내 답안 조회</button><button id="teamResultsButton" class="secondary-button" type="button">우리 조 결과</button><button id="allResultsButton" class="secondary-button" type="button">전체 조 결과</button></div><div class="result-grid">${visible.length?visible.map(renderSubmissionCard).join(""):`<p class="muted">아직 제출된 결과가 없습니다.</p>`}</div></section>`;views.results.querySelector("#myAnswersButton").addEventListener("click",renderMyAnswers);views.results.querySelector("#teamResultsButton").addEventListener("click",()=>renderResults("team"));views.results.querySelector("#allResultsButton").addEventListener("click",()=>renderResults("all"));views.results.querySelectorAll("[data-feedback-form]").forEach(form=>form.addEventListener("submit",handleFeedbackSubmit));showView("results");}
function renderSubmissionCard(submission){const element=findElementByAtomicNumber(submission.elementNumber);const items=state.feedback.filter(item=>item.submissionId===submission.id);return `<article class="card stack"><div class="submission-meta"><span class="pill">${escapeHtml(submission.gradeName||"")}</span><span class="pill">${escapeHtml(submission.className)}</span><span class="pill">${escapeHtml(submission.teamName)}</span><span class="pill">${escapeHtml(submission.studentNumber)}번 ${escapeHtml(submission.studentName)}</span><span class="pill">${submission.questionIndex}번</span></div><img class="submission-image" src="${submission.imageData}" alt="${escapeHtml(submission.studentName)} 제출 이미지">${renderAnswerSummary(submission,element)}${state.settings.answerRevealEnabled?renderCorrectAnswer(element):`<p class="muted">정답 확인은 선생님이 열어주면 볼 수 있습니다.</p>`}<div><h3>피드백</h3><div class="feedback-list">${items.length?items.map(renderFeedback).join(""):`<p class="muted">아직 피드백이 없습니다.</p>`}</div><form data-feedback-form="${submission.id}" class="stack"><textarea name="message" required placeholder="친구에게 도움이 되는 피드백을 적어주세요."></textarea><button type="submit">피드백 등록</button></form></div></article>`;}
function renderAnswerSummary(submission,element){return `<div class="table-wrap"><table><tbody><tr><th>출제 원소</th><td>${element?`${element.name} (${element.symbol})`:submission.elementNumber}</td></tr><tr><th>학생 입력</th><td>${Object.entries(submission.studentAnswers||{}).map(([key,value])=>`${FIELD_LABELS[key]}: ${escapeHtml(value)}`).join("<br>")}</td></tr></tbody></table></div>`;}
function renderCorrectAnswer(element){return `<div class="stack"><h3>정답 원자 모형</h3>${renderAtomSvg(element)}</div>`;}
function renderFeedback(item){return `<div class="feedback-item"><strong>${escapeHtml(item.fromStudentName)}</strong>: ${escapeHtml(item.message)}</div>`;}
async function handleFeedbackSubmit(event){event.preventDefault();const form=event.currentTarget;try{await saveFeedback({submissionId:form.dataset.feedbackForm,sessionId:state.sessionId,fromClassName:state.profile.className,fromGradeName:state.profile.gradeName,fromTeamName:state.profile.teamName,fromStudentNumber:state.profile.studentNumber,fromStudentName:state.profile.studentName,message:clean(new FormData(form).get("message"))});await renderResults("all");}catch(error){showMessage(`피드백 저장 실패: ${error.message}`,true);}}

async function renderMyAnswers(){const submissions=(await listSessionSubmissions(state.sessionId)).sort((a,b)=>Number(a.questionIndex)-Number(b.questionIndex));views.myAnswers.innerHTML=`<section class="panel stack"><div><h2>내 제출 답안</h2><p class="muted">현재 참여에서 제출한 답안만 볼 수 있습니다.</p></div><div class="actions"><button id="refreshAllowanceButton" class="secondary-button" type="button">권한 새로고침</button><button id="backResultsButton" class="secondary-button" type="button">결과로 돌아가기</button></div><div class="result-grid">${submissions.map(item=>`<article class="card stack"><h3>${item.questionIndex}번 답안</h3><img class="submission-image" src="${item.imageData}" alt="내 ${item.questionIndex}번 답안"><p class="muted">${item.submissionType==="canvas"?"캔버스":"사진"} 제출 · 수정 가능 ${Number(item.editAllowance||0)}회</p>${Number(item.editAllowance||0)>0?`<button data-edit-answer="${item.id}" type="button">수정하기</button>`:""}</article>`).join("")}</div></section>`;views.myAnswers.querySelector("#refreshAllowanceButton").addEventListener("click",renderMyAnswers);views.myAnswers.querySelector("#backResultsButton").addEventListener("click",()=>renderResults("team"));views.myAnswers.querySelectorAll("[data-edit-answer]").forEach(button=>button.addEventListener("click",()=>renderAnswerEditor(submissions.find(item=>item.id===button.dataset.editAnswer))));showView("myAnswers");}
function renderAnswerEditor(submission){views.myAnswers.innerHTML=`<section class="panel stack"><h2>${submission.questionIndex}번 답안 수정</h2><form id="answerEditForm" class="stack">${submissionEditorMarkup(submission.imageData)}<div class="actions"><button type="submit">수정 저장</button><button id="cancelEditButton" class="secondary-button" type="button">취소</button></div></form></section>`;bindSubmissionEditor(views.myAnswers,{mode:submission.submissionType||"photo",photoData:submission.submissionType!=="canvas"?submission.imageData:""});views.myAnswers.querySelector("#cancelEditButton").addEventListener("click",renderMyAnswers);views.myAnswers.querySelector("#answerEditForm").addEventListener("submit",async event=>{event.preventDefault();try{await replaceSubmissionResult(submission.id,await getEditorResult());showMessage("답안을 수정했습니다.");await renderMyAnswers();}catch(error){showMessage(error.message,true);}});showView("myAnswers");}

function renderAdminLogin(){views.admin.innerHTML=`<section class="panel stack"><h2>관리자 접속</h2><form id="adminLoginForm" class="stack"><label>Gmail 아이디 <span class="gmail-input"><input name="identifier" required><span>@gmail.com</span></span></label><label>비밀번호 <input name="password" type="password" required></label><div class="actions"><button type="submit">접속</button><button id="cancelAdminButton" class="secondary-button" type="button">취소</button></div></form></section>`;views.admin.querySelector("#adminLoginForm").addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await signInAdmin(data.get("identifier"),data.get("password"));await renderAdminDashboard();}catch(error){showMessage(`관리자 로그인 실패: ${error.message}`,true);}});views.admin.querySelector("#cancelAdminButton").addEventListener("click",renderStart);showView("admin");}
async function renderAdminDashboard(){await migrateLegacyVisibility();await refreshSettings();await refreshClassData(true);state.adminRecords=groupParticipationRecords(state.submissions,state.sessions);views.admin.innerHTML=`<section class="panel stack"><div><h2>관리자 화면</h2><p class="muted">참여 기록을 선택하면 제출물을 한 문제씩 확인할 수 있습니다.</p></div><div class="actions"><button id="adminHomeButton" class="secondary-button" type="button">홈</button><button id="adminLogoutButton" class="secondary-button" type="button">로그아웃</button></div><div class="grid"><label class="switch-row">정답 확인 허용 <input id="answerToggle" type="checkbox" ${state.settings.answerRevealEnabled?"checked":""}></label><label class="switch-row">원소 검색 허용 <input id="searchToggle" type="checkbox" ${state.settings.elementSearchEnabled?"checked":""}></label></div><label>학생 검색 <input id="adminFilter" placeholder="학년, 반, 조, 번호, 이름"></label><div id="adminParticipationList" class="participant-list"></div></section>`;views.admin.querySelector("#adminHomeButton").addEventListener("click",renderStart);views.admin.querySelector("#adminLogoutButton").addEventListener("click",async()=>{await signOutAdmin();renderStart();});views.admin.querySelector("#answerToggle").addEventListener("change",handleSettingChange);views.admin.querySelector("#searchToggle").addEventListener("change",handleSettingChange);views.admin.querySelector("#adminFilter").addEventListener("input",renderAdminParticipationList);renderAdminParticipationList();showView("admin");}
function renderAdminParticipationList(){const keyword=clean(views.admin.querySelector("#adminFilter")?.value).toLowerCase();const records=state.adminRecords.filter(record=>!keyword||`${record.gradeName} ${record.className} ${record.teamName} ${record.studentNumber} ${record.studentName}`.toLowerCase().includes(keyword));const root=views.admin.querySelector("#adminParticipationList");root.innerHTML=records.length?records.map(record=>`<article class="participant-row"><button data-open-session="${record.sessionId}" class="participant-main secondary-button" type="button"><strong>${escapeHtml(record.gradeName)} ${escapeHtml(record.className)} ${escapeHtml(record.teamName)} ${escapeHtml(record.studentNumber)}번 ${escapeHtml(record.studentName)}</strong><span>${record.submissions.length}개 제출 · ${record.visibleToPeers?"다른 학생 조회 가능":"다른 학생 조회 불가능"}</span></button><button data-toggle-session="${record.sessionId}" class="secondary-button" type="button">${record.visibleToPeers?"조회 불가능으로":"조회 가능으로"}</button><button data-delete-session="${record.sessionId}" class="danger-button" type="button">전체 삭제</button></article>`).join(""):`<p class="muted">조건에 맞는 참여 기록이 없습니다.</p>`;root.querySelectorAll("[data-open-session]").forEach(button=>button.addEventListener("click",()=>openAdminModal(button.dataset.openSession)));root.querySelectorAll("[data-toggle-session]").forEach(button=>button.addEventListener("click",async()=>{const record=state.adminRecords.find(item=>item.sessionId===button.dataset.toggleSession);await setSessionPeerVisibility(record.sessionId,!record.visibleToPeers);await renderAdminDashboard();}));root.querySelectorAll("[data-delete-session]").forEach(button=>button.addEventListener("click",async()=>{const record=state.adminRecords.find(item=>item.sessionId===button.dataset.deleteSession);const label=`${record.gradeName} ${record.className} ${record.studentNumber}번 ${record.studentName}`;if(!confirm(`${label} 학생의 참여 기록, 제출물, 피드백을 모두 삭제하시겠습니까?`))return;await deleteParticipation(record.sessionId);showMessage("학생 참여 기록을 모두 삭제했습니다.");await renderAdminDashboard();}));}
async function handleSettingChange(){await saveSettings({answerRevealEnabled:views.admin.querySelector("#answerToggle").checked,elementSearchEnabled:views.admin.querySelector("#searchToggle").checked});showMessage("관리자 설정을 저장했습니다.");}
function openAdminModal(sessionId){state.adminRecord=state.adminRecords.find(item=>item.sessionId===sessionId);if(!state.adminRecord.submissions.length){showMessage("아직 제출된 답안이 없습니다.",true);return;}state.adminPage=0;history.pushState({adminModal:true},"");renderAdminModal();}
function renderAdminModal(){const submission=state.adminRecord.submissions[state.adminPage];const page=createAdminPopupPage(submission,state.feedback);modalHost.innerHTML=`<div class="modal-backdrop"><section class="answer-modal" role="dialog" aria-modal="true"><div class="modal-header"><div><span class="pill">${state.adminPage+1} / ${state.adminRecord.submissions.length}</span><h2>${escapeHtml(state.adminRecord.studentName)} · ${page.questionIndex}번 답안</h2></div><button data-close-modal class="secondary-button" type="button">닫기 ×</button></div><img class="submission-image" src="${page.imageData}" alt="학생 제출 결과물"><div><h3>피드백</h3><div class="feedback-list">${page.feedback.length?page.feedback.map(renderFeedback).join(""):`<p class="muted">피드백이 없습니다.</p>`}</div></div><p class="muted">남은 수정 권한: ${page.editAllowance}회</p><div class="actions"><button data-grant-edit type="button">수정 권한 1회 부여</button><button data-download class="secondary-button" type="button">그림 다운로드</button></div><div class="modal-nav"><button data-prev class="secondary-button" type="button" ${state.adminPage===0?"disabled":""}>← 이전</button><button data-next type="button" ${state.adminPage>=state.adminRecord.submissions.length-1?"disabled":""}>다음 →</button></div></section></div>`;document.body.classList.add("modal-open");modalHost.querySelector("[data-close-modal]").addEventListener("click",()=>history.back());modalHost.querySelector(".modal-backdrop").addEventListener("click",event=>event.target===event.currentTarget&&history.back());modalHost.querySelector("[data-prev]").addEventListener("click",()=>{state.adminPage-=1;renderAdminModal();});modalHost.querySelector("[data-next]").addEventListener("click",()=>{state.adminPage+=1;renderAdminModal();});modalHost.querySelector("[data-grant-edit]").addEventListener("click",async()=>{await grantSubmissionEdit(page.id);page.editAllowance+=1;state.adminRecord.submissions[state.adminPage].editAllowance=page.editAllowance;renderAdminModal();});modalHost.querySelector("[data-download]").addEventListener("click",()=>downloadSubmission(page));let swipeStart=null;const modal=modalHost.querySelector(".answer-modal");modal.addEventListener("pointerdown",event=>swipeStart=event.clientX);modal.addEventListener("pointerup",event=>{if(swipeStart==null)return;const distance=event.clientX-swipeStart;swipeStart=null;if(distance< -60&&state.adminPage<state.adminRecord.submissions.length-1){state.adminPage+=1;renderAdminModal();}else if(distance>60&&state.adminPage>0){state.adminPage-=1;renderAdminModal();}});}
function closeAdminModal(useHistory=true){if(useHistory)return history.back();modalHost.innerHTML="";document.body.classList.remove("modal-open");state.adminRecord=null;}
function downloadSubmission(submission){const link=document.createElement("a");link.href=submission.imageData;link.download=makeDownloadFilename(submission);document.body.append(link);link.click();link.remove();}

function renderSearch(){if(!state.settings.elementSearchEnabled)return showMessage("원소 검색은 선생님이 열어주면 사용할 수 있습니다.",true);views.search.innerHTML=`<section class="panel stack"><h2>원소 검색</h2><label>검색어 <input id="elementSearchInput" placeholder="예: 산소, O, 8"></label><div id="searchResults" class="result-grid"></div><button id="backToStartButton" class="secondary-button" type="button">돌아가기</button></section>`;const input=views.search.querySelector("#elementSearchInput");input.addEventListener("input",()=>renderSearchResults(input.value));views.search.querySelector("#backToStartButton").addEventListener("click",()=>state.profile?renderResults("team"):renderStart());renderSearchResults("");showView("search");}
function renderSearchResults(keyword){const value=clean(keyword).toLowerCase();const results=getSearchPool().filter(element=>!value||String(element.atomicNumber).includes(value)||element.name.toLowerCase().includes(value)||element.symbol.toLowerCase().includes(value));views.search.querySelector("#searchResults").innerHTML=results.map(element=>`<article class="card">${renderCorrectAnswer(element)}</article>`).join("");}
