import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, onAuthStateChanged, signInAnonymously, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { addDoc, collection, doc, getDoc, getDocs, getFirestore, increment, orderBy, query, runTransaction, serverTimestamp, setDoc, updateDoc, where, writeBatch } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { isAdminUid, normalizeGmailAddress } from "./auth-utils.js";
const firebaseConfig={apiKey:"AIzaSyCMrXcbMrqjcxtIVtHFK4kRGqCCshx8O9A",authDomain:"atom-quiz2026.firebaseapp.com",projectId:"atom-quiz2026",storageBucket:"atom-quiz2026.firebasestorage.app",messagingSenderId:"215913928615",appId:"1:215913928615:web:47a7822c3d065e41dac882"};
const app=initializeApp(firebaseConfig);const auth=getAuth(app);const db=getFirestore(app);const DEFAULT_SETTINGS={answerRevealEnabled:false,elementSearchEnabled:false};
export async function ensureAnonymousStudent(){await waitForAuth();if(!auth.currentUser)await signInAnonymously(auth);return auth.currentUser;}
export async function signInAdmin(identifier,password){if(auth.currentUser)await signOut(auth);const credential=await signInWithEmailAndPassword(auth,normalizeGmailAddress(identifier),password);if(!isAdminUid(credential.user.uid)){await signOut(auth);await signInAnonymously(auth);throw new Error("관리자 권한이 없는 계정입니다.");}return credential.user;}
export async function signOutAdmin(){await signOut(auth);await signInAnonymously(auth);}
export function getCurrentUser(){return auth.currentUser;}
export function isCurrentUserAdmin(){return isAdminUid(auth.currentUser?.uid);}
export async function createSession(profile){const user=await ensureAnonymousStudent();const ref=await addDoc(collection(db,"sessions"),{...profile,ownerUid:user.uid,visibleToPeers:true,createdAt:serverTimestamp(),completedAt:null});return ref.id;}
export async function completeSession(sessionId){await updateDoc(doc(db,"sessions",sessionId),{completedAt:serverTimestamp()});}
export async function saveSubmission(submission){const user=await ensureAnonymousStudent();const ref=await addDoc(collection(db,"submissions"),{...submission,ownerUid:user.uid,visibleToPeers:true,editAllowance:0,modifiedAt:null,submittedAt:serverTimestamp()});return ref.id;}
export async function listSubmissions({admin=false}={}){if(admin&&isCurrentUserAdmin())return readQuery(query(collection(db,"submissions"),orderBy("submittedAt","desc")));const user=await ensureAnonymousStudent();const [visible,owned]=await Promise.all([readQuery(query(collection(db,"submissions"),where("visibleToPeers","==",true))),readQuery(query(collection(db,"submissions"),where("ownerUid","==",user.uid)))]);return dedupe([...visible,...owned]).sort(sortSubmitted);}
export async function listSessionSubmissions(sessionId){if(isCurrentUserAdmin())return readQuery(query(collection(db,"submissions"),where("sessionId","==",sessionId)));const user=await ensureAnonymousStudent();return readQuery(query(collection(db,"submissions"),where("sessionId","==",sessionId),where("ownerUid","==",user.uid)));}
export async function listSessions(){if(!isCurrentUserAdmin())throw new Error("관리자 권한이 필요합니다.");return readQuery(query(collection(db,"sessions"),orderBy("createdAt","desc")));}
export async function saveFeedback(feedback){const user=await ensureAnonymousStudent();const ref=await addDoc(collection(db,"feedback"),{...feedback,ownerUid:user.uid,createdAt:serverTimestamp()});return ref.id;}
export async function listFeedback(submissionIds=[],{admin=false}={}){if(admin&&isCurrentUserAdmin()&&!submissionIds.length)return readQuery(query(collection(db,"feedback"),orderBy("createdAt","asc")));const snapshots=await Promise.all(submissionIds.map(id=>readQuery(query(collection(db,"feedback"),where("submissionId","==",id)))));return snapshots.flat().sort((a,b)=>timestamp(a.createdAt)-timestamp(b.createdAt));}
export async function getSettings(){const ref=doc(db,"settings","app");const snapshot=await getDoc(ref);if(!snapshot.exists()){if(isCurrentUserAdmin())await setDoc(ref,{...DEFAULT_SETTINGS,updatedAt:serverTimestamp()});return {...DEFAULT_SETTINGS};}return {...DEFAULT_SETTINGS,...snapshot.data()};}
export async function saveSettings(settings){await setDoc(doc(db,"settings","app"),{answerRevealEnabled:Boolean(settings.answerRevealEnabled),elementSearchEnabled:Boolean(settings.elementSearchEnabled),updatedAt:serverTimestamp()},{merge:true});}
export async function grantSubmissionEdit(submissionId){await updateDoc(doc(db,"submissions",submissionId),{editAllowance:increment(1)});}
export async function replaceSubmissionResult(submissionId,result){await runTransaction(db,async transaction=>{const ref=doc(db,"submissions",submissionId);const snapshot=await transaction.get(ref);const allowance=Number(snapshot.data()?.editAllowance||0);if(!snapshot.exists()||allowance<1)throw new Error("수정 권한이 없습니다.");transaction.update(ref,{imageData:result.imageData,submissionType:result.submissionType,editAllowance:allowance-1,modifiedAt:serverTimestamp()});});}
export async function setSessionPeerVisibility(sessionId,visibleToPeers){const submissions=await listSessionSubmissions(sessionId);const batch=writeBatch(db);batch.update(doc(db,"sessions",sessionId),{visibleToPeers});submissions.forEach(item=>batch.update(doc(db,"submissions",item.id),{visibleToPeers}));await batch.commit();}
export async function deleteParticipation(sessionId,{studentCancel=false}={}){const submissions=await listSessionSubmissions(sessionId);const feedback=studentCancel||!submissions.length?[]:await listFeedback(submissions.map(item=>item.id),{admin:isCurrentUserAdmin()});const batch=writeBatch(db);feedback.forEach(item=>batch.delete(doc(db,"feedback",item.id)));submissions.forEach(item=>batch.delete(doc(db,"submissions",item.id)));batch.delete(doc(db,"sessions",sessionId));await batch.commit();}
export async function migrateLegacyVisibility(){if(!isCurrentUserAdmin())return;const [sessions,submissions]=await Promise.all([readQuery(collection(db,"sessions")),readQuery(collection(db,"submissions"))]);const missing=[...sessions.filter(item=>typeof item.visibleToPeers!=="boolean").map(item=>["sessions",item.id]),...submissions.filter(item=>typeof item.visibleToPeers!=="boolean").map(item=>["submissions",item.id])];if(!missing.length)return;const batch=writeBatch(db);missing.forEach(([name,id])=>batch.update(doc(db,name,id),{visibleToPeers:true}));await batch.commit();}
function readQuery(queryRef){return getDocs(queryRef).then(snapshot=>snapshot.docs.map(item=>({id:item.id,...item.data()})));}
function waitForAuth(){return new Promise(resolve=>{const unsubscribe=onAuthStateChanged(auth,()=>{unsubscribe();resolve();});});}
function dedupe(items){return [...new Map(items.map(item=>[item.id,item])).values()];}
function timestamp(value){return value?.toMillis?.()||Number(value?.seconds||0)*1000;}
function sortSubmitted(a,b){return timestamp(b.submittedAt)-timestamp(a.submittedAt);}
